import { Geist_Mono, Nunito_Sans } from "next/font/google";

import "./globals.css";
import { cn } from "@/lib/utils";

import type { Metadata } from "next";

const nunitoSans = Nunito_Sans({ subsets: ["latin"], variable: "--font-sans" });

const fontMono = Geist_Mono({
  subsets: ["latin"],
  variable: "--font-mono",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="vi"
      className={cn(
        "antialiased",
        fontMono.variable,
        "font-sans",
        nunitoSans.variable,
        "h-full"
      )}
    >
      <body className="flex min-h-full flex-col">{children}</body>
    </html>
  );
}
