-- ╔══════════════════════════════════════════════════════════════╗
-- ║  Phase 1: Data Migration (must run before DROP TABLE users) ║
-- ╚══════════════════════════════════════════════════════════════╝

-- Copy password_hash from users to students (only where missing)
UPDATE students SET password_hash = users.password_hash
FROM users
WHERE students.user_id = users.user_id
  AND students.password_hash IS NULL;--> statement-breakpoint

-- Create staff records for BTC / CHECKIN_STAFF users not yet in staff table
INSERT INTO staff (email, full_name, password_hash, role, is_active, created_at)
SELECT u.email, COALESCE(u.full_name, u.email), u.password_hash,
       u.role::text::staff_role,
       CASE WHEN u.status = 'ACTIVE' THEN true ELSE false END,
       u.created_at
FROM users u
LEFT JOIN staff s ON s.email = u.email
WHERE s.staff_id IS NULL
  AND u.role IN ('BTC', 'CHECKIN_STAFF');--> statement-breakpoint

-- Map checkin_records.checked_in_by: old users.userId → new staff.staffId
UPDATE checkin_records cr
SET checked_in_by = s.staff_id
FROM users u
JOIN staff s ON s.email = u.email
WHERE cr.checked_in_by = u.user_id;--> statement-breakpoint

-- Map workshop_documents.uploaded_by: old users.userId → new staff.staffId
UPDATE workshop_documents wd
SET uploaded_by = s.staff_id
FROM users u
JOIN staff s ON s.email = u.email
WHERE wd.uploaded_by = u.user_id;--> statement-breakpoint

-- ╔══════════════════════════════════════════════════════════════╗
-- ║  Phase 2: Schema Migration (DDL generated by Drizzle Kit)   ║
-- ╚══════════════════════════════════════════════════════════════╝

ALTER TABLE "users" DISABLE ROW LEVEL SECURITY;--> statement-breakpoint
DROP TABLE "users" CASCADE;--> statement-breakpoint
ALTER TABLE "checkin_staff_assignments" RENAME COLUMN "user_id" TO "staff_id";--> statement-breakpoint
ALTER TABLE "checkin_staff_assignments" DROP CONSTRAINT "uq_checkin_staff_assignments_user";--> statement-breakpoint
ALTER TABLE "workshop_documents" DROP CONSTRAINT "workshop_documents_uploaded_by_users_user_id_fk";
--> statement-breakpoint
ALTER TABLE "checkin_staff_assignments" DROP CONSTRAINT "checkin_staff_assignments_user_id_users_user_id_fk";
--> statement-breakpoint
ALTER TABLE "students" DROP CONSTRAINT "students_user_id_users_user_id_fk";
--> statement-breakpoint
ALTER TABLE "checkin_records" DROP CONSTRAINT "checkin_records_checked_in_by_users_user_id_fk";
--> statement-breakpoint
DROP INDEX "idx_checkin_staff_assignments_user";--> statement-breakpoint
DROP INDEX "idx_students_user_id";--> statement-breakpoint
ALTER TABLE "students" ALTER COLUMN "password_hash" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "workshop_documents" ADD CONSTRAINT "workshop_documents_uploaded_by_staff_staff_id_fk" FOREIGN KEY ("uploaded_by") REFERENCES "public"."staff"("staff_id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "checkin_staff_assignments" ADD CONSTRAINT "checkin_staff_assignments_staff_id_staff_staff_id_fk" FOREIGN KEY ("staff_id") REFERENCES "public"."staff"("staff_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "checkin_records" ADD CONSTRAINT "checkin_records_checked_in_by_staff_staff_id_fk" FOREIGN KEY ("checked_in_by") REFERENCES "public"."staff"("staff_id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "idx_checkin_staff_assignments_staff" ON "checkin_staff_assignments" USING btree ("staff_id");--> statement-breakpoint
ALTER TABLE "students" DROP COLUMN "user_id";--> statement-breakpoint
ALTER TABLE "checkin_staff_assignments" ADD CONSTRAINT "uq_checkin_staff_assignments_staff" UNIQUE("staff_id");--> statement-breakpoint
DROP TYPE "public"."user_role";--> statement-breakpoint
DROP TYPE "public"."user_status";
