/**
 * Shared context object that flows through every stage of the AI summary pipeline.
 *
 * Acts as the "Pipe" in the Pipe-and-Filter architecture — each filter reads
 * its required input from the context and writes its output back into it after
 * processing. This decouples filters from each other's shapes: a filter only
 * knows the fields it produces and consumes, not the full pipeline graph.
 *
 * Fields are progressively populated as the context passes through filters:
 * - Before any filter: `documentId`, `workshopId`, `fileUrl` (from the job data)
 * - After Upsert: `summaryId`
 * - After Extract: `rawText`
 * - After Clean: `cleanedText`
 * - After LLM: `summaryText`, `modelUsed`
 */
export interface PdfPipelineContext {
  /** UUID of the workshop document being summarised. */
  readonly documentId: string;
  /** UUID of the associated workshop. */
  readonly workshopId: string;
  /** Object-storage URL of the PDF file. */
  readonly fileUrl: string;
  /** UUID of the upserted ai_summaries record (set by UpsertRecordFilter). */
  summaryId?: string;
  /** Raw text extracted from the PDF (set by PdfExtractionFilter). */
  rawText?: string;
  /** Cleaned and normalised text ready for the LLM (set by TextCleaningFilter). */
  cleanedText?: string;
  /** Summary text generated by the LLM (set by LlmSummaryFilter). */
  summaryText?: string;
  /** AI model identifier used for the summary (set by LlmSummaryFilter). */
  modelUsed?: string;
}

/**
 * Creates a new pipeline context from job data.
 *
 * Factory function ensures that all required fields are present at
 * construction time while optional output fields remain undefined.
 *
 * @param documentId - UUID of the workshop document.
 * @param workshopId - UUID of the associated workshop.
 * @param fileUrl - Object-storage URL of the PDF file.
 * @returns A new pipeline context with only the input fields set.
 */
export function createPipelineContext(
  documentId: string,
  workshopId: string,
  fileUrl: string
): PdfPipelineContext {
  return { documentId, workshopId, fileUrl };
}
